// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoDtI6GxYINWvKR8t_BxbngGA4yL7NRFM',
    appId: '1:186705679131:web:7496fc6a68f3a7ceff79be',
    messagingSenderId: '186705679131',
    projectId: 'alard-56d33',
    authDomain: 'alard-56d33.firebaseapp.com',
    storageBucket: 'alard-56d33.firebasestorage.app',
    measurementId: 'G-FVSPT8NFVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOqA_nMBFu4VkdmSoJnP4CZeWkrXptG4c',
    appId: '1:186705679131:android:08a4975a6d7e899bff79be',
    messagingSenderId: '186705679131',
    projectId: 'alard-56d33',
    storageBucket: 'alard-56d33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWe7-tGiOjqK-Ttn1ryZWu3bDzSREdhj4',
    appId: '1:186705679131:ios:6e73a129b94f5771ff79be',
    messagingSenderId: '186705679131',
    projectId: 'alard-56d33',
    storageBucket: 'alard-56d33.firebasestorage.app',
    iosBundleId: 'com.example.alardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWe7-tGiOjqK-Ttn1ryZWu3bDzSREdhj4',
    appId: '1:186705679131:ios:6e73a129b94f5771ff79be',
    messagingSenderId: '186705679131',
    projectId: 'alard-56d33',
    storageBucket: 'alard-56d33.firebasestorage.app',
    iosBundleId: 'com.example.alardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoDtI6GxYINWvKR8t_BxbngGA4yL7NRFM',
    appId: '1:186705679131:web:82383ad41ba3f336ff79be',
    messagingSenderId: '186705679131',
    projectId: 'alard-56d33',
    authDomain: 'alard-56d33.firebaseapp.com',
    storageBucket: 'alard-56d33.firebasestorage.app',
    measurementId: 'G-FHKZ6RGVTY',
  );
}
